# Generated by Django 5.2.6 on 2025-09-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100, verbose_name="Company")),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Position Title"),
                ),
                (
                    "applicationStatus",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Applied",
                        verbose_name="Application Status",
                    ),
                ),
                ("dateApplied", models.DateField(verbose_name="Date Applied")),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link to Application"
                    ),
                ),
                ("domain", models.CharField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
